# Generated by Django 4.2.1 on 2023-07-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_sellerproductprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='en_name',
            field=models.CharField(max_length=150, verbose_name='English Name'),
        ),
    ]
